---
- resource_group: Development_Team
  vm_name: VM1
  ports:
  - '22'
  - '80'
  - '443'
  image:
    publisher: Canonical
    offer: UbuntuServer
    sku: 18.04-LTS
    version: latest
  vm_size: Standard_B1ls
  admin_user: azureuser
  admin_password: your_admin_pass
- resource_group: Research_Team
  vm_name: VM2
  ports:
  - '22'
  - '80'
  - '443'
  image:
    publisher: Canonical
    offer: 0001-com-ubuntu-server-focal
    sku: 20_04-lts-gen2
    version: latest
  vm_size: Standard_B1ls
  admin_user: azureuser
  admin_password: your_admin_pass
- resource_group: Marketing_Team
  vm_name: VM3
  ports:
  - '22'
  - '80'
  - '443'
  image:
    publisher: Canonical
    offer: 0001-com-ubuntu-server-focal
    sku: 20_04-lts-gen2
    version: latest
  vm_size: Standard_B1ls
  admin_user: azureuser
  admin_password: your_admin_pass
